### ISSUE TITLE
Failed to install requirements: openai>=1.3.8 and tiktoken

### ISSUE THREAD

**Issue by jake32321** [zhaobenny/bz-cogs#23]
Currently running into this issue after upgrading Red. Might need some assistance knowing what can be done to resolve this issue.

```[2023-12-19 17:18:35] [ERROR] red.downloader: Something went wrong when installing the following requirements: openai>=1.3.8
[2023-12-19 17:18:52] [ERROR] red.downloader: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
red-discordbot 3.5.5 requires charset-normalizer==3.2.0, but you have charset-normalizer 3.3.2 which is incompatible.
red-discordbot 3.5.5 requires idna==3.4, but you have idna 3.6 which is incompatible.
ERROR: Exception:
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 510, in run
    self._handle_target_dir(
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 565, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/lib/python3.11/shutil.py", line 738, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.11/shutil.py", line 736, in rmtree
    os.rmdir(path, dir_fd=dir_fd)
OSError: [Errno 39] Directory not empty: '/data/cogs/Downloader/lib/regex'
[2023-12-19 17:18:52] [ERROR] red.downloader: Something went wrong when installing the following requirements: tiktoken
[2023-12-19 17:23:42] [ERROR] red.downloader: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
red-discordbot 3.5.5 requires idna==3.4, but you have idna 3.6 which is incompatible.
red-discordbot 3.5.5 requires typing-extensions==4.7.1, but you have typing-extensions 4.9.0 which is incompatible.
ERROR: Exception:
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 510, in run
    self._handle_target_dir(
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 565, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/lib/python3.11/shutil.py", line 738, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.11/shutil.py", line 736, in rmtree
    os.rmdir(path, dir_fd=dir_fd)
OSError: [Errno 39] Directory not empty: '/data/cogs/Downloader/lib/pydantic_core'```

**Comment by jake32321** [comment]
Scratch that. Some serious weirdness with Docker the python environment if I had to guess. Restarting docker altogether fixed it. 😛
